// See https://aka.ms/new-console-template for more information
using carenirvana.bre;

Console.WriteLine("Hello, World!");

var startTime = DateTime.Now;
Console.WriteLine($"start time: {startTime}");
var rEngine = new RuleEngine(File.ReadAllText(@"D:\repos\carenirvana-bre\src\carenirvana.bre.testapp\BREConfigData.json"));
// rEngine.ExecuteRules("");
var output = rEngine.ExecuteRule("OutpatientTransportationAutoApprove", ["Outpatient - Transportation", "Approved", "A0130"]);
Console.WriteLine($"run completed...");
var endTime = DateTime.Now;
Console.WriteLine($"end time: {endTime}");
Console.WriteLine($"Time taken to process : {new TimeSpan(DateTime.Now.Ticks - startTime.Ticks)}");

Console.ReadLine();

// 1 mil (input table)
// batches
// read (threads) 1st batch, 2nd batch, 3rd batch
// rule transformation -- threads
// 

// member id : 1 CouldBeDiabetic : true  -- output (add activity into a table)
// member id : 2 CouldBeDiabetic : false - no action


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------