<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Impl\Postgres\" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Npgsql" Version="9.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\carenirvana.bre.common\carenirvana.bre.common.csproj" />
	  <ProjectReference Include="..\carenirvana.bre.model\carenirvana.bre.model.csproj" />
	</ItemGroup>
</Project>
